// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type CreateLobbyPayload struct {
	Lobby *Lobby `json:"lobby"`
}

type Lobby struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Public bool   `json:"public"`
}

func (Lobby) IsNode()            {}
func (this Lobby) GetID() string { return this.ID }

type SigninPayload struct {
	User *User `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }
