volumes:
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.config/gcloud/application_default_credentials.json:/workspaces/.config/gcloud/application_default_credentials.json:ro
    command: sleep infinity
    networks:
      - default
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
  redis:
    image: "redis:latest"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
networks:
  default:
