version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.config/gcloud/application_default_credentials.json:/workspaces/.config/gcloud/application_default_credentials.json:ro
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
