version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.config/gcloud/application_default_credentials.json:/workspaces/.config/gcloud/application_default_credentials.json:ro
    command: sleep infinity
    networks:
      - default
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: "redis:latest"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
networks:
  default:
