name: Deploy to Cloud Run (development)

on:
  push:
    tags:
      - v*

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - region: asia-northeast1
    environment:
      name: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.CLOUD_RUN_DEPLOY_PROVIDER }}
          service_account: ${{ vars.SA_CLOUD_RUN_DEPLOY }}

      - uses: google-github-actions/setup-gcloud@v1

      - uses: ko-build/setup-ko@v0.6
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build and Deploy
        env:
          KO_DOCKER_REPO: asia-northeast1-docker.pkg.dev/${{ vars.PROJECT_ID }}/trivia-backend
          KO_CONFIG_PATH: .ko.yaml
        run: |
          gcloud run deploy trivia-backend \
            --region ${{ matrix.region }} \
            --allow-unauthenticated \
            --concurrency=1 \
            --cpu=1 \
            --max-instances=1 \
            --min-instances=0 \
            --image $(ko build --platform=linux/amd64 -B) \
            --set-env-vars MYSQL_USER=${{ secrets.MYSQL_USER }} \
            --set-env-vars MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            --set-env-vars MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
            --set-env-vars MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            --set-env-vars MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --set-env-vars REDIS_HOST=${{ secrets.REDIS_HOST }} \
            --set-env-vars REDIS_PORT=${{ secrets.REDIS_PORT }} \
            --set-env-vars REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --set-env-vars REDIS_DB=${{ secrets.REDIS_DB }} \
            --quiet
